---
# config.yaml for GATK pipeline

# List of sample IDs
samples:
  - Sample1
  - Sample2
  - Sample3

# List of genomic intervals (e.g., chromosomes) for parallel processing
intervals:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX
  - chrY

# Paths to reference data and resources
paths:
  ref_genome: "reference/Homo_sapiens_assembly38.fasta"
  bam_dir: "analysis_ready_bams"
  resources:
    dbsnp: "resources/dbsnp_146.hg38.vcf.gz"
    hapmap: "resources/hapmap_3.3.hg38.vcf.gz"
    omni: "resources/1000G_omni2.5.hg38.vcf.gz"
    phase1: "resources/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
    mills: "resources/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"

# Parameters for tools
params:
  java_opts: "-Xmx8g"
  vqsr:
    snp_sensitivity: "99.5"
    indel_sensitivity: "99.0"
