---
name: wgs_analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Core tools
  - python=3.9
  - openjdk=11
  - pip

  # Workflow management
  - snakemake-minimal

  # Alignment and preprocessing
  - bwa
  - samtools
  - picard
  - trimmomatic

  # Variant calling
  - gatk4

  # SV/CNV calling tools
  - manta
  - delly
  - lumpy-sv
  - cnvnator
  - survivor

  # QC and utilities
  - fastqc
  - multiqc
  - bcftools
  - tabix

  # Annotation
  - snpeff
  - ensembl-vep
  - annotsv
